{{- if .Values.cloudflare.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-free-exporter.fullname" . }}
  labels:
    {{- include "cloudflare-free-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cloudflare.existingSecretKey }}: {{ required "cloudflare.token is required when cloudflare.create is true" .Values.cloudflare.token | quote }}
{{- end }}
